### PR TITLE
Open in...

### PR DESCRIPTION
**Pull request by ennerperez**
Contextual menu to "Open with actions..."

image

- Open in Fleet
- Open in Visual Studio Code

### CODE REVIEW

**Comment by love-linger** [comment]
I've tested your PR. The functionality is complete. 

But using the `Avalonia.Svg` increase the size for final exe from 37MB to 42MB! Then I converts these two SVG icon to PNG image with 64x64 size and removed reference for `Avalonia.SVG`. After that the size of 
 final exe comes back to 37MB. 

So, I suggest use PNG instead of SVG for this PR.

**Comment by ennerperez** [comment]
There is a file size limit for the final exe? I think the usage of Avalonia.Svg worth it. specially to improve the UI, add new icons, and make it scalable for different resolutions, I have to test it in high DPI resolution when probably PNG quality is not good enough.

**Comment by love-linger** [comment]
> There is a file size limit for the final exe? I think the usage of Avalonia.Svg worth it. specially to improve the UI, add new icons, and make it scalable for different resolutions, I have to test it in high DPI resolution when probably PNG quality is not good enough.

No, there's no limitations for the size of final exe. But in this project, SVG only used to display the external editor icons. I think it's not worth to introduce a new package since we can use `RenderOptions.BitmapInterpolationMode="HighQuality"` to get a similar result with built-in PNG support.

**Comment by ennerperez** [comment]
What happened with the menu?

**Comment by love-linger** [comment]
Now, only external tools detected by the software are displayed.

**Pull request merged**
