### PR TITLE
 Make search filter launcher page specific

### PR DESCRIPTION
**Pull request by aikawayataro**
This will make the search filter tabbed (draft concept)
Just a concept to show how I think #398 could look like

### CODE REVIEW

**Comment by love-linger** [comment]
For the following reasons, this PR will not be merged into the repository.

* I am skeptical about the necessity and rationality of the requirement of "needing to open multiple `Welcome` pages for managing or querying repositories".
* Since the datasource behind the view is a single piece of data (`ViewModels.Preference.Instance`), even if multiple `Welcome` pages are optimized and some of the data is stored separately, there are still some synchronization behaviours when performing multi-page operations. For example, as mentioned earlier, after expanding a certain group on one `Welcome` page, the same group on all other `Welcome` pages should also be expanded (because the `IsExpanded` state of the group will be saved in `preference.json`, and if the data is inconsistent, it is impossible to determine which one to use).
* The current implementation method makes it easier for users to perceive that the data on the `Welcome` page is actually one piece, which can better guide users on how to use this page.

In the original design, I wanted users to use the page like they use `Ctrl + P` in VSCode, for example:

* `Ctrl+T` to open a new Welcome page
* Enter the partial name of the repository in search box
* Use Up/Down keys to select the repository to be opened
* Press `Enter` key to open the repository

**Comment by aikawayataro** [comment]
> I am skeptical about the necessity and rationality of the requirement of "needing to open multiple Welcome pages for managing or querying repositories".

There is at least one major reason for me: when you open a repository after using search, the new tab (or other Welcome tabs) will contain the same search query. Could be confusing, I have to clear search filter manually this way.

> Since the datasource behind the view is a single piece of data (ViewModels.Preference.Instance), even if multiple Welcome pages are optimized and some of the data is stored separately, there are still some synchronization behaviours when performing multi-page operations. For example, as mentioned earlier, after expanding a certain group on one Welcome page, the same group on all other Welcome pages should also be expanded (because the IsExpanded state of the group will be saved in preference.json, and if the data is inconsistent, it is impossible to determine which one to use).

The draft implementation in this PR doesn't affect this behavior, as it only restores the search filter. The tabs are still "synced" as before, expanded groups are expanded everywhere. There is still a single `Welcome` instance.

> The current implementation method makes it easier for users to perceive that the data on the Welcome page is actually one piece, which can better guide users on how to use this page.

I can't argue with that, but PR doesn't change anything here. It still feels "synced" because nothing has changed from the original behavior.

> In the original design, I wanted users to use the page like they use Ctrl + P in VSCode, for example:

I see. But if you go with tabs, I think used approach brings more confusion.

Thank you for taking a look! Feel free to close this PR. I just wanted to make sure you saw the point I was trying to make :grin:

**Comment by love-linger** [comment]
> There is at least one major reason for me: when you open a repository after using search, the new tab (or other Welcome tabs) will contain the same search query. Could be confusing, I have to clear search filter manually this way.

So what's the meaning if people only search some repository after a `Welcome` page opened, and then open another `Welcome` page if they want to search again?

**Comment by aikawayataro** [comment]
> So what's the meaning if people only search some repository after a Welcome page opened, and then open another Welcome page if they want to search again?

I meant, for example, if I open SourceGit and use search to find the repo, then open a new tab to open a second one, the previous search is still there.
The latest change sort of fixes that, and I think we're done here.
As for the change I suggested, well, there's no practical purpose to having multiple tabs with their search filters. This behavior just seems natural to me.

**Pull request closed without merging**
