### PR TITLE
Use ArgumentList for commands instead of manual escaping

### PR DESCRIPTION
**Pull request by aikawayataro**
This will refactor command arguments from a single string to an argument array

Argument arrays are easier to work with, and you don't have to worry about escaping arguments. They are also easier to work with because you can split them into multiple lines

I've tested all the features I use, but an extra pair of eyes is really needed :grin:

### CODE REVIEW

**Comment by love-linger** [comment]
BTW, I don't think using 'ArgumentList' is better than 'Arguments' since we have manually escaped the path strings and when creating a specified process, the parameter list is always concated into a single string.

**Comment by aikawayataro** [comment]
Manual escaping is bug-prone and may fail if path contains `"` with the current implementation. 
But the main reason in `ArgumentList` is to provide a more robust and secure way to provide arguments. It is simply easier to work with array than string.

> when creating a specified process, the parameter list is always concated into a single string

https://source.dot.net/#System.Diagnostics.Process/System/Diagnostics/Process.Unix.cs,2cbba2bbbfb82be9

Maybe on Windows. Before this dotnet will parse command to argv anyway, later passed to `execve` inside native interop

In the end, the main goal of this PR is to make commands more readable and easier to maintain

**Comment by aikawayataro** [comment]
I can address the issues, but how do you feel about the change in general? No worries if you don't need this

**Comment by love-linger** [comment]
> I can address the issues, but how do you feel about the change in general? No worries if you don't need this

Both ways are fine for me. I don't have any preference.

**Pull request closed without merging**
