### PR TITLE
fix: invalidate counter visual (#338)

### PR DESCRIPTION
**Pull request by gadfly3173**
Keep the same implementation as `CommitRefsPresenter` to avoid displaying the number of the previous `DataContext`

### CODE REVIEW

**Comment by love-linger** [comment]
`CommitRefsPresenter` depends on `DataContext` to draw contents. But `CounterPresenter` only depends on its own property `CountProperty` to draw contents.

```csharp
static CounterPresenter()
{
    AffectsMeasure<CounterPresenter>(
        FontSizeProperty,
        FontFamilyProperty,
        ForegroundProperty,
        CountProperty);

    AffectsRender<CounterPresenter>(
        ForegroundProperty,
        BackgroundProperty,
        CountProperty);
}
```

The issue #338 still exists about this control?

**Comment by gadfly3173** [comment]
> The issue #338 still exists about this control?

The current situation is that after switching repo, the number of the previous repo may be displayed instead of 0. After making this change, I cannot reproduce the problem here.

**Comment by gadfly3173** [comment]
> `CommitRefsPresenter` depends on `DataContext` to draw contents. But `CounterPresenter` only depends on its own property `CountProperty` to draw contents.
> 
> ```cs
> static CounterPresenter()
> {
>     AffectsMeasure<CounterPresenter>(
>         FontSizeProperty,
>         FontFamilyProperty,
>         ForegroundProperty,
>         CountProperty);
> 
>     AffectsRender<CounterPresenter>(
>         ForegroundProperty,
>         BackgroundProperty,
>         CountProperty);
> }
> ```

It seems that `OnDataContextChanged` can be removed.

**Comment by love-linger** [comment]
Since you have added the `InvalidateVisual` in the end of `MeasureOverride`, I suggest you to remove the `CountProperty` from `AffectsRender` call.

**Comment by gadfly3173** [comment]
Confirmed that `AffectsRender` can be all removed.

**Pull request merged**
