### PR TITLE
supported accept repository path from cli

### PR DESCRIPTION
**Pull request by seayxu**
supported accept repository path from cli

```ps
sourcegit.exe D:\code\tmp\sourcegit
```

### CODE REVIEW

**Comment by love-linger** [comment]
1. If you start this app without custom commandline args, it will crash.

image

2. If you have enable `Restore windows` and the last time you shutdown this app with opened repository tabs, there will be no `Welcome` page opened on startup. 

image

And after started, if you open a new tab, it will just replaced to the repository that specified by the commandline. It's very strange.

**Comment by love-linger** [comment]
And it's not recommanded to do this in `Views`. Instead, it should be implemented in `ViewModels`.

**Comment by seayxu** [comment]
Fixed crash without path, to implement this in `View` is fast.

**Comment by love-linger** [comment]
I've pushed my implementation for this feature. 

The disadvantage of implementing in `Views.Welcome` is that it will not work until you have a welcome page.

**Comment by love-linger** [comment]
For example, this is the behavior with your PR:

https://github.com/sourcegit-scm/sourcegit/assets/4075673/f991af5f-08f8-4d24-ac2f-0b8aa2c28b70

**Pull request closed without merging**
