### PR TITLE
Make the side panel scroll as a whole

### PR DESCRIPTION
**Pull request by Noisyfox**
This works much better on small screens when repo has lots of tags and branches

side_scroll

### CODE REVIEW

**Comment by love-linger** [comment]
If whole panel is scrollable, virtualizing will not work. This can cause stalling when displaying a large number of lists or tree nodes.

**Comment by love-linger** [comment]
for example, this is a user's repo from issue #215, which has 1900+ tags

image

**Comment by Noisyfox** [comment]
Firstly the tags are not shown by default. Secondly they can always filter first, if they really have THAT many tags.

**Comment by Noisyfox** [comment]
My main complatination is even ignore the tags, currently the branch list cannot be properly used on small screens.

**Comment by Noisyfox** [comment]
At the moment, if you have a lot of local branches, you couldn't even see the remotes list nor submodules, not mention tags.
image

**Comment by Noisyfox** [comment]
> > At the moment, if you have a lot of local branches, you couldn't even see the remotes list nor submodules, not mention tags. image
> 
> This is indeed a disaster.
> 
> For a redesign, I would focus on two things
> 
> * Need to support virtualization so that it doesn't get stuck when there are many items
> * Each group should be easily found at any time. For example, if you are scrolling through a list with 1000+ tags, you should also be able to see the grouping of local branches in that state, rather than having to scroll back.

Yeah agreed.

**Comment by love-linger** [comment]
I've pushed a new implementation for this. You can try it with latest develop branch

**Comment by Noisyfox** [comment]
> I've pushed a new implementation for this. You can try it with latest develop branch

That's much better now! Thanks! I can daily drive this instead of SourceTree now~ Fantastic work man!

**Comment by love-linger** [comment]
I've pushed a new commit for this feature. You can try the latest build

**Pull request closed without merging**
