### PR TITLE
feature: replace "to Here" in context menu  with SHA of selected commit

### PR DESCRIPTION
**Pull request by wl2776**
Word "to Here" do not seem grammatically correct to me.

Therefore I've decided to make this menu better.
I have also reworded a couple of other messages in Russian locale.

I am not sure about correctness of messages in other languages, besides English and Russian. Please, revise and fix them.

### CODE REVIEW

**Comment by love-linger** [comment]
In my opinion, switching to SHA is more difficult for users to understand. 

I've checked that how `SourceTree`, `Fork` and `Gitkraken` implement this. None of them using SHA in the context of selected commit.  

* SourceTree
image
image

* Fork
image
image

* Gitkraken
image
image

**Comment by wl2776** [comment]
> I've checked that how `SourceTree`, `Fork` and `Gitkraken` implement this. None of them using SHA in the context of selected commit.

Please, take a closer look at SourceTree screenshots. Its context menus say "Rebase children of 44a784a interactively..."  and "Rebase children of 81a0e2a59 interactively..." 

image

SmartGit's menus simply say "Rebase..."

Anyway, I don't think that the sentence "Rebase xxxx to Here" is grammatically correct. It should be "Rebase xxxx here".

**Comment by love-linger** [comment]
> > I've checked that how `SourceTree`, `Fork` and `Gitkraken` implement this. None of them using SHA in the context of selected commit.
> 
> Please, take a closer look at SourceTree screenshots. Its context menus say "Rebase children of 44a784a interactively..." and "Rebase children of 81a0e2a59 interactively..."
> 
> image

You just pointed out the part which I did not like. When users selected a commit and open context menu of it, why not using a friendly name such as `This Commit` or `Here` to reference the one they just selected? If we shows an SHA, do we want them to check what this SHA reference to?
 
> SmartGit's menus simply say "Rebase..."
> 
> Anyway, I don't think that the sentence "Rebase xxxx to Here" is grammatically correct. It should be "Rebase xxxx here" or "Rebase xxxx to selected commit".

I will change the `Rebase xxxx to Here` to `Rebase xxxx on Here`

image

**Comment by wl2776** [comment]
> I will change the `Rebase xxxx to Here` to `Rebase xxxx on Here`

Please, change the message to "Rebase xxxx on this commit". 

"Here" is not a [proper noun](https://en.wikipedia.org/wiki/Proper_noun), therefore should not start from the capital "H".
And "Rebase to here" is the grammatically incorrect construction. I've never seen "to here" in high-quality English texts.

**Comment by wl2776** [comment]
And regarding another commit in this PR, [66d413a](https://github.com/sourcegit-scm/sourcegit/pull/811/commits/66d413a42a63d5c479bfa4bff05c93b87ccbc0c3)

It seems to me that Russian messages is a low-quality result of automatic translation. I'd like to keep fixes that I've made in it.

**Comment by love-linger** [comment]
> > I will change the `Rebase xxxx to Here` to `Rebase xxxx on Here`
> 
> Please, change the message to "Rebase xxxx on this commit".
> 
> "Here" is not a [proper noun](https://en.wikipedia.org/wiki/Proper_noun), therefore should not start from the capital "H". And "Rebase to here" seems to me grammatically incorrect construction. High-quality English texts that I've seen, use "to here" in other contexts and constructions. Unfortunately, I'm not an expert in English grammar, therefore cannot name specific rules that govern this.

I do NOT think so. Here is a screenshot from `JetBrains Rider`
image

**Comment by wl2776** [comment]
> I do NOT think so. Here is a screenshot from `JetBrains Rider` 

Hmm. This seems reasonable. Although JetBrains developers have Russian roots, I don't think that their knowledge of English is poor.

**Comment by wl2776** [comment]
> I'd like to keep fixes that I've made in [66d413a](https://github.com/sourcegit-scm/sourcegit/commit/66d413a42a63d5c479bfa4bff05c93b87ccbc0c3).

I'll do it in another PR. I need to consult with existing translation of the ProGit book.

**Pull request closed without merging**
