### PR TITLE
Fix: Enhance support of worktree repository

### PR DESCRIPTION
**Pull request by gadfly3173**
Partial repair #86 

- added force refresh branches and commits after operated branch.
- fixed watcher

Known Issues:
- Operate branch and commit in other worktree repo(includes base repo) still won't show in current worktree repo. To solve this may need to add refresh branches and commits after switched repo tab.
- Manually press `FETCH` button won't fix above question.

### CODE REVIEW

**Comment by love-linger** [comment]
commit 27fd5829f57bcc004c3c4daf8169edb076c0869d will not be merged because it will introduce some issues:

* If you pressed middle button on the tab but release it outside the tab-bar, the _middleButtonPressed will never be reset to `false`
* If you pressed middle button on one tab but release it on another tab, the behaviour is very strange.

**Comment by love-linger** [comment]
According to the code in `Models/Watcher.cs`:

```csharp
if (_updateBranch > 0 && now > _updateBranch)
{
    _updateBranch = 0;
    _updateWC = 0;

    if (_updateTags > 0)
    {
        _updateTags = 0;
        Task.Run(() =>
        {
            _repo.RefreshTags();
            _repo.RefreshBranches();
            _repo.RefreshCommits();
        });
    }
    else
    {
        Task.Run(() =>
        {
            _repo.RefreshBranches();
            _repo.RefreshCommits();
        });
    }

    Task.Run(_repo.RefreshWorkingCopyChanges);
}
```

`Repository.RefershBranches` and `Repository.RefreshCommits` will always be called if the state of branch changes. If you want to run it immediately, I suggest you use `Repository.MarkBranchesDirtyManually` in UIThread instead. For example:

```diff
-               CallUIThread(() => _repo.SetWatcherEnabled(true));
-               if (!CheckoutAfterCreated)
-               {
-                   _repo.RefreshBranches();
-                   _repo.RefreshCommits();
-               }
+               CallUIThread(() => {
+                   repo.SetWatcherEnabled(true);
+                   repo.MarkBranchesDirtyManually();
+               });
                return true;
```

**Comment by love-linger** [comment]
By the way, would adding a toolbar button to refresh the entire repository (shortcut F5) help with these and other similar issue?

**Comment by gadfly3173** [comment]
I'll continue to work on this after April 30th.

**Comment by love-linger** [comment]
There are already three ways to close tabs.

* Click the close button on each tab (with left mouse button)
* Use context menu of each tab (with right mouse button)
* Use hotkey `CTRL + W`

I really do NOT want to introduce a nother way that using the mouse middle button……

**Comment by gadfly3173** [comment]
> There are already three ways to close tabs.
> 
> * Click the close button on each tab (with left mouse button)
> * Use context menu of each tab (with right mouse button)
> * Use hotkey `CTRL + W`
> 
> I really do NOT want to introduce a nother way that using the mouse middle button……

Using the middle button to close a tab is a very common design in other multi-tab applications, such as Chrome, Jetbrains IDE, Visual Studio Code, GitKraken, etc.

**Comment by gadfly3173** [comment]
> Known Issues:
> 
> * Operate branch and commit in other worktree repo(includes base repo) still won't show in current worktree repo. To solve this may need to add refresh branches and commits after switched repo tab.
> * Manually press `FETCH` button won't fix above question.

Fixed these issues

**Comment by love-linger** [comment]
Commit a63a0d10fbf644221e86ac2031a94c40c26d6a4c force refreshing branches, working copy changes and commit after current active page changed. It's not recommanded.

**Comment by gadfly3173** [comment]
> Commit [a63a0d1](https://github.com/sourcegit-scm/sourcegit/commit/a63a0d10fbf644221e86ac2031a94c40c26d6a4c) force refreshing branches, working copy changes and commit after current active page changed. It's not recommanded. I've add a hotkey 'F5' to manually refresh the whole repository if it is needed.

Why is it not recommended to refresh branches, commits, and workspaces after switching repositories? According to my observation, GitKraken takes this approach.

**Pull request closed without merging**
