### PR TITLE
Add children list to the commit base info view

### PR DESCRIPTION
**Pull request by czarkoff**
Useful for navigation between the commits.

The implementation is suboptimal.  It would probably make more sense to search for children when the view is displayed, but that would require much more substantial changes as currently commit list is not available in the view.

That said, in my testing this implementation appears to perform acceptably.

### CODE REVIEW

**Comment by czarkoff** [comment]
FWIW to me it would make sense to change parent and children lists from `List<string>` to `List<Commit>`. That would also allow for showing tooltips with useful info in the details view.

**Comment by love-linger** [comment]
To be honest, I don't really like this feature - especially the design of `Children`.

> FWIW to me it would make sense to change parent and children lists from List<string> to List<Commit>. That would also allow for showing tooltips with useful info in the details view.

I also don't agree with this modification. Relevant, if necessary, I will provide a custom text block control that used to display `Commit.SHA`. Only when its content changes will it asynchronously obtain the information needed for tooltips.

**Comment by czarkoff** [comment]
You don't find this feature useful in principle, or you would prefer a different implementation?  An alternative would be to search for the commit's children when it is being displayed.  Or maybe you have some other idea?

**Comment by czarkoff** [comment]
I've reverted the previous attempt and made another one. This time children are fetched asynchronously for a specific commit while the view is being rendered.  If I understood your feedback correctly, that should be more in line with your approach.

Now, it is possible that I didn't understand your feedback correctly.  If that is the case,  I would appreciate if you could explain what kind of implementation for this feature you would like to see.  Or close the PR if you don't regard this functionality as a desirable feature.

Either way I hope I didn't waste too much of your time unnecessarily,  and I am really sorry if I did.

**Comment by love-linger** [comment]
Nice job. It's better now.

**Comment by love-linger** [comment]
I'm sorry. I will revert this PR due to the performance of `Commands.QueryCommitChildren`. It takes more than 2 seconds on my PC (AMD 7950X).

**Comment by czarkoff** [comment]
I see.  It was much faster with repos I tried, so thank you for the pointer at a better test. I will look into this next weekend.

**Pull request merged**
