### PR TITLE
style(locale): Translate to French Batch 2

### PR DESCRIPTION
**Pull request by UchiTesting**
A second batch of translation for French locale.

The translation should be roughly 2/3 to completion.

Bellow is a non exhaustive list of changes.

Diff.SyntaxHighlight
RevealFile
Revert
Reword
Running
Save
Stash
URL
UpdateSubmodules
Warn
WorkingCopy
Worktree

Some extra sentences

Include small fixes for
CodeEditor : missing accent
Include a fix mentioned in the previous PR #405 but not merged. (non -> nom for name in a string)

### CODE REVIEW

**Comment by UchiTesting** [comment]
Good evening.

Can I use the occasion to ask a question.

In the confirmation dialog to drop a stash, I see a "On" term I cannot understand where it comes from.

image

There are 2 strings that contain such text but they are both followed by a colon (:) and changing them did not help.

I should translate this to "sur"

The code seems to be located in Views/DropStash.axaml but I can't find where the "On" comes from.

```xml
      <StackPanel Grid.Column="1" Orientation="Horizontal">
        <Path Width="12" Height="12" Margin="0,0,8,0"
              HorizontalAlignment="Left" VerticalAlignment="Center"
              Data="{StaticResource Icons.Stashes}"/>

        <TextBlock VerticalAlignment="Center" Classes="primary" Text="{Binding Stash.SHA, Converter={x:Static c:StringConverters.ToShortSHA}}" Foreground="DarkOrange"/>
        <TextBlock VerticalAlignment="Center" Text="{Binding Stash.Message}" Margin="8,0,0,0"/>
      </StackPanel>
```

**Comment by love-linger** [comment]
I suggest you work with the authors of PR #424 to merge the changes into a final PR.

**Comment by love-linger** [comment]
> Good evening.
> 
> Can I use the occasion to ask a question?
> 
> In the confirmation dialog to drop a stash, I see a "On" term I cannot understand where it comes from.
> 
> image
> 
> There are 2 strings that contain such text but they are both followed by a colon (:) and changing them did not help.
> 
> I should translate this to "sur"
> 
> The code seems to be located in _Views/DropStash.axaml_ but I can't find where the "On" comes from.
> 
> ```
>       <StackPanel Grid.Column="1" Orientation="Horizontal">
>         <Path Width="12" Height="12" Margin="0,0,8,0"
>               HorizontalAlignment="Left" VerticalAlignment="Center"
>               Data="{StaticResource Icons.Stashes}"/>
> 
>         <TextBlock VerticalAlignment="Center" Classes="primary" Text="{Binding Stash.SHA, Converter={x:Static c:StringConverters.ToShortSHA}}" Foreground="DarkOrange"/>
>         <TextBlock VerticalAlignment="Center" Text="{Binding Stash.Message}" Margin="8,0,0,0"/>
>       </StackPanel>
> ```

It's the stash message and added by `git` automatically. You can see:
image

**Comment by UchiTesting** [comment]
OK Thanks.
So this can't be helped.

**Comment by UchiTesting** [comment]
> I suggest you work with the authors of PR #424 to merge the changes into a final PR.

I saw that. And at first I thought the same. However after a second thought I think we can merge my changes (delta any potential thing to fix) 1st and then go for the improvement batch.
I did comment about it in the other PR too.

I will review the lines submitted there and halt progress with the remaining 3rd of translations.

**Pull request merged**
