### PR TITLE
Few terminal fixes

### PR DESCRIPTION
**Pull request by aikawayataro**
* Fix crash on Welcome screen
* Allow custom terminal and non-absolute executable names for terminals (useful when setting a custom terminal)
* Catch errors thrown by `Process.Start` when terminal configuration is invalid on Linux

### CODE REVIEW

**Comment by yitzchak-ben-ezra-ecoplant** [comment]
Suggestion: if terminal not specified open a default one
For example in Mac the native terminal

**Comment by ybeapps** [comment]
Suggestion: if terminal not specified open a default one
For example in Mac the native terminal

I think it’s better than raising errors

**Comment by love-linger** [comment]
Please keep the target branch of your PR to `develop` the next time.

**Comment by aikawayataro** [comment]
Me again, really sorry 😬

**Pull request merged**
